[book]
language = "zh-CN"
title = "Agora Book - Agroa.io 应用开发指南"
authors = ["白宦成 <bestony@linux.com>"]
description = "这是一本 Agora 实战应用开发经验集合，总结了作者在开发 NESHouse 和 NESHouse Pro 版本时的心得体会。"
multilingual = false
src = "src"

[build]
create-missing = true
[output.html]
google-analytics = "G-N2MS64YPM9"
git-repository-url = "https://github.com/bestony/Agora-Development-Book"
git-repository-icon = "fa-github"
[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true